### ISSUE TITLE
Problem downloading example

### ISSUE THREAD

**Issue by echavess** [BackTrackBB/backtrackbb#1]
Hi, 

Could you please provide an example of to create the grids?
and if you have a configuration file for tremor, that I can use as "template" with my own data, would be fantastic. Sorry, many questions, but I think the code is pretty good and I am very interested in locating some tremor in Costa Rica. 

Thanks in advance, 
Esteban

**Comment by npoiata** [comment]
Hi Esteban,

It is strange. I do not have any problem with uncompressing the zip file. Might be a problem with your connection? Could you try again later and if it won't work I will put it somewhere else and send you a new link? The file is rather big since it contains both data and grids, so, I will not be able to mail it to you.
Examples of the grids are inside the examples.zip file. To create your own grids you can use NonLinLoc (Vel2Grid and Grid2Time routines), see here:http://alomax.free.fr/nlloc/ (also see in http://backtrackbb.readthedocs.io/en/latest/how_to.html).

For switching between the characteristic functions (kurtosis envelope) use 
'ch_function' parameter (ch_function=kurtosis or ch_function=envelope). More details about the config parameters are here: http://backtrackbb.readthedocs.io/en/latest/how_to.html#config-file-and-parameters.

Hope it helps

**Comment by echavess** [comment]
Hi Natalia, 

Thanks very much. I just downloaded the data from github's link. Don't know why the other didn't work for me. I will try the examples now. I have seen the ch_function also. Thanks very much!

**Comment by npoiata** [comment]
ok, good!
